databases:
  - name: paste_safe
    plan: free
    databaseName: Paste
    user: user

services:
  - type: web
    plan: free
    name: paste_secure
    runtime: python
    buildCommand: "./paste_secure/build.sh"
    startCommand: "python -m gunicorn paste_secure.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
