# Generated by Django 5.0.2 on 2024-02-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='hashed_password',
        ),
        migrations.AddField(
            model_name='paste',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
