# Generated by Django 5.0.2 on 2024-02-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0002_remove_paste_hashed_password_paste_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='password',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
